# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobuf import slurm_pb2 as protobuf_dot_slurm__pb2


class SlurmctldServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.cmd = channel.unary_unary(
        '/proto.SlurmctldService/cmd',
        request_serializer=protobuf_dot_slurm__pb2.CMDRequest.SerializeToString,
        response_deserializer=protobuf_dot_slurm__pb2.ResultResponse.FromString,
        )


class SlurmctldServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def cmd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SlurmctldServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'cmd': grpc.unary_unary_rpc_method_handler(
          servicer.cmd,
          request_deserializer=protobuf_dot_slurm__pb2.CMDRequest.FromString,
          response_serializer=protobuf_dot_slurm__pb2.ResultResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.SlurmctldService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
