# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/slurm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/slurm.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14protobuf/slurm.proto\x12\x05proto\"q\n\nCMDRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.proto.CMDRequest.CMD\"1\n\x03\x43MD\x12\t\n\x05SINFO\x10\x00\x12\x08\n\x04SRUN\x10\x01\x12\n\n\x06SQUEUE\x10\x02\x12\t\n\x05SACCT\x10\x03\" \n\x0eResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2E\n\x10SlurmctldService\x12\x31\n\x03\x63md\x12\x11.proto.CMDRequest\x1a\x15.proto.ResultResponse\"\x00\x62\x06proto3')
)



_CMDREQUEST_CMD = _descriptor.EnumDescriptor(
  name='CMD',
  full_name='proto.CMDRequest.CMD',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINFO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SRUN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQUEUE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SACCT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=95,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_CMDREQUEST_CMD)


_CMDREQUEST = _descriptor.Descriptor(
  name='CMDRequest',
  full_name='proto.CMDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='proto.CMDRequest.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.CMDRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMDREQUEST_CMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=144,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='ResultResponse',
  full_name='proto.ResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.ResultResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=178,
)

_CMDREQUEST.fields_by_name['type'].enum_type = _CMDREQUEST_CMD
_CMDREQUEST_CMD.containing_type = _CMDREQUEST
DESCRIPTOR.message_types_by_name['CMDRequest'] = _CMDREQUEST
DESCRIPTOR.message_types_by_name['ResultResponse'] = _RESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMDRequest = _reflection.GeneratedProtocolMessageType('CMDRequest', (_message.Message,), dict(
  DESCRIPTOR = _CMDREQUEST,
  __module__ = 'protobuf.slurm_pb2'
  # @@protoc_insertion_point(class_scope:proto.CMDRequest)
  ))
_sym_db.RegisterMessage(CMDRequest)

ResultResponse = _reflection.GeneratedProtocolMessageType('ResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESULTRESPONSE,
  __module__ = 'protobuf.slurm_pb2'
  # @@protoc_insertion_point(class_scope:proto.ResultResponse)
  ))
_sym_db.RegisterMessage(ResultResponse)



_SLURMCTLDSERVICE = _descriptor.ServiceDescriptor(
  name='SlurmctldService',
  full_name='proto.SlurmctldService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=180,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='cmd',
    full_name='proto.SlurmctldService.cmd',
    index=0,
    containing_service=None,
    input_type=_CMDREQUEST,
    output_type=_RESULTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLURMCTLDSERVICE)

DESCRIPTOR.services_by_name['SlurmctldService'] = _SLURMCTLDSERVICE

# @@protoc_insertion_point(module_scope)
