# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from test.protobuf import user_pb2 as protobuf_dot_user__pb2


class UserServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserById = channel.unary_unary(
        '/proto.UserService/GetUserById',
        request_serializer=protobuf_dot_user__pb2.DetailRequest.SerializeToString,
        response_deserializer=protobuf_dot_user__pb2.User.FromString,
        )
    self.GetUsers = channel.unary_unary(
        '/proto.UserService/GetUsers',
        request_serializer=protobuf_dot_user__pb2.QueryUserListRequest.SerializeToString,
        response_deserializer=protobuf_dot_user__pb2.UserList.FromString,
        )


class UserServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserById': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserById,
          request_deserializer=protobuf_dot_user__pb2.DetailRequest.FromString,
          response_serializer=protobuf_dot_user__pb2.User.SerializeToString,
      ),
      'GetUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=protobuf_dot_user__pb2.QueryUserListRequest.FromString,
          response_serializer=protobuf_dot_user__pb2.UserList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
